In [ ]:
import numpy as np
import matplotlib
import sys
import matplotlib.pyplot as plt
import time
sys.path.append('/home/codio/workspace/.guides/hf')
from helper import *


%matplotlib inline
print('You\'re running python %s' % sys.version.split(' ')[0])

You're running python 3.9.16


# **The Perceptron**
The perceptron is a basic linear classifier. The following cells will walk you through steps and ask you to finish the necessary functions in a pre-defined order. Code cells requiring your input will display # YOUR CODE HERE and graded portions will be adequately labeled. Unless specified otherwise, do not use loops.

# **Part One: Perceptron Update **[Graded]
Implement the function below to update the perceptron given an input vector, label, and weight vector. Do not check if an update is necessary. This function can assume that it is only called when an update should be performed. Hint: You simply need to implement 𝐰←𝐰+𝑦𝐱
.

In [ ]:
def perceptron_update(x,y,w):
    """
    function w=perceptron_update(x,y,w);

    Updates the perceptron weight vector w using x and y
    Input:
    x : input vector of d dimensions (d)
    y : corresponding label (-1 or +1)
    w : weight vector of d dimensions

    Output:
    w : weight vector after updating (d)
    """
    # YOUR CODE HERE

    update = np.multiply(y,x)
    w_new = w+update
    return w_new

    raise NotImplementedError()

In [ ]:
# little test
y = -1
x = np.random.randint(low=-2, high=2, size=10)
w = np.random.randint(low=0, high=2, size=10)*2 - 1
print(f'y\t= {y}')
print(f'x\t= {x}')
print(f'w_old\t= {w}')

y	= -1
x	= [ 1  0  0  0 -1 -2 -2  0  0  1]
w_old	= [ 1  1  1  1  1  1  1  1  1 -1]


In [ ]:
update = np.dot(y,x)
print(update)

[-1  0  0  0  1  2  2  0  0 -1]


In [ ]:
update = y*x
print(update)

[-1  0  0  0  1  2  2  0  0 -1]


In [ ]:
update = np.multiply(y,x)
print(update)

[-1  0  0  0  1  2  2  0  0 -1]


In [ ]:
w_new = w+update
print(w_new)

[ 0  1  1  1  2  3  3  1  1 -2]


In [ ]:
w_new.T

array([ 0,  1,  1,  1,  2,  3,  3,  1,  1, -2])

In [ ]:
w_new.T*x

array([ 0,  0,  0,  0, -2, -6, -6,  0,  0, -2])

In [ ]:
w_new @ x

-16

In [ ]:
w_new.dot(x.T)

-16

In [ ]:
w_new = perceptron_update(x, y, w)
print(f'w_new\t= {w_new}')

TypeError: ignored

# **Part Two: Implement Perceptron** [Graded]
Implement function perceptron. This should contain a loop that calls perceptron_update until it converges or the maximum iteration count, 100, has been reached. Make sure you randomize the order of the training data on each iteration (you can use np.random.permutation() to do this.)

We assume that the  𝑑𝑡ℎ
  dimension of  𝐱𝑖
  is 1, and so the last dimension of  𝐰
  represents the bias term, which we implicitly absorbed into the weight vector. So you can implement the pseudocode directly.

In [ ]:
def perceptron(xs, ys):
    """
    function w=perceptron(xs,ys);

    Returns the weight vector learned by the Perceptron classifier.
    We assume that the last dimension of each xs is 1.

    Input:
    xs : n input vectors of d dimensions (nxd matrix)
    ys : n labels (-1 or +1)

    Output:
    w : weight vector (d)
    b : bias term
    """

    n, d = xs.shape     # so we have n input vectors, of d dimensions each
    w = np.zeros(d)
    b = 0.0
    iter = 0
    m = 0

    for i in np.random.permutation(n): #to randomise the order of the training data on each iteration
        classified = y[i]*(w.T*x[i]+ b) #
        while classified <= 0:
            iter +=1
            w += perceptron_update
            b +=y
        if classified >0:
            break
        elif iter == n:
            break
    return w, b

    raise NotImplementedError()

There are several issues with this code:

The function perceptron_update is not defined, so it will raise a NameError when the function is called.
The variable y is not defined. It is likely that ys is supposed to be used instead.
The line b += y should be b += ys[i], as ys is the array containing the labels, and we need to use the label corresponding to the current input vector.
The line classified = y[i]*(w.T*x[i]+ b) should be classified = ys[i]*(np.dot(w, xs[i]) + b), as ys is the array containing the labels, and we should use np.dot to compute the dot product of the weight vector and the input vector.
The break statement inside the loop will terminate the loop prematurely, so the function may not converge to a solution.

In [ ]:
import numpy as np

def perceptron(xs, ys):
    """
    function w=perceptron(xs,ys);

    Returns the weight vector learned by the Perceptron classifier.
    We assume that the last dimension of each xs is 1.

    Input:
    xs : n input vectors of d dimensions (nxd matrix)
    ys : n labels (-1 or +1)

    Output:
    w : weight vector (d)
    b : bias term
    """

    n, d = xs.shape     # so we have n input vectors, of d dimensions each
    w = np.zeros(d)
    b = 0.0
    iter = 0

    while True: #while loop continues until a condition is met
        for i in np.random.permutation(n):
            if ys[i]*(np.dot(w, xs[i]) + b) <= 0: #if misclassified
                w += np.multiply(ys[i],xs[i]) #update corresponding weight with yx for that input vector
                b += ys[i] #update corresponding bias with y for that input vector
        iter += 1 #update iteration number
        if ys[i]*(np.dot(w, xs[i]) + b) > 0 or iter == n: #if classified correctly, or maximum iterations
            break #end the loop

    return w, b #and return the latest updated w and b


In [ ]:
N = 100
d = 10

In [ ]:
x = np.random.rand(N,d)
w = np.random.rand(1,d)

In [ ]:
def test_Perceptron1():
    N = 100;
    d = 10;
    x = np.random.rand(N,d)
    w = np.random.rand(1,d)
    y = np.sign(w.dot(x.T))[0]
    w, b = perceptron(x,y)
    preds = classify_linear_grader(x,w,b)
    return np.array_equal(preds.reshape(-1,),y.reshape(-1,))

In [ ]:
def test_Perceptron2():
    x = np.array([ [-0.70072, -1.15826],  [-2.23769, -1.42917],  [-1.28357, -3.52909],  [-3.27927, -1.47949],  [-1.98508, -0.65195],  [-1.40251, -1.27096],  [-3.35145,-0.50274],  [-1.37491,-3.74950],  [-3.44509,-2.82399],  [-0.99489,-1.90591],   [0.63155,1.83584],   [2.41051,1.13768],  [-0.19401,0.62158],   [2.08617,4.41117],   [2.20720,1.24066],   [0.32384,3.39487],   [1.44111,1.48273],   [0.59591,0.87830],   [2.96363,3.00412],   [1.70080,1.80916]])
    y = np.array([1]*10 + [-1]*10)
    w, b =perceptron(x,y)
    preds = classify_linear_grader(x,w,b)
    return np.array_equal(preds.reshape(-1,),y.reshape(-1,))

Once you have perceptron implemented, we can visualize how it finds w that classify points in a 2-dimensional plane. In this example, we center the data by subtracting the common mean vector of  𝐱𝑖
  from each of  𝐱𝑖
 . Consequently, the perceptron algorithm will learn the bias term (the last dimension of  𝐰
  as 0).

In [ ]:
def plot_perceptron_2D(x, y_true, w_true, y_pred, w_pred, b):
    w_pred = w_pred.flatten()
    w_true = w_true.flatten()

    fig = plt.figure(figsize=(10, 10))
    # Plot points
    plt.scatter(x[:, 0], x[:, 1], c=y_true, cmap='viridis')

    grid_lim = np.max(abs(x[:, :-1]))

    def calc_x2(b, x1, w):
        return -(b+w[0] * x1) / w[1]

    # Make arrow for w_true: normalize by magnitude, then stretch to grid lim
    w_true_mag = np.sqrt(np.sum(w_true[:-1] ** 2))
    plt.quiver([0], [0], [(w_true[0] / w_true_mag) * grid_lim], [(w_true[1] / w_true_mag) * grid_lim],
               scale=1, units='xy', color='k')
    plt.annotate('w_true', xy=w_true[:-1] / w_true_mag * grid_lim + [.05, 0.], fontsize=12, color='k')

    # Make decision line perpendicular to arrow
    plt.plot([grid_lim, -grid_lim], [calc_x2(b, grid_lim, w_true), calc_x2(b, -grid_lim, w_true)],
             color='k', label='true decision line')

    # Repeat for w_pred
    w_pred_mag = np.sqrt(np.sum(w_pred[:-1] ** 2))
    plt.quiver([0], [0], [(w_pred[0] / w_pred_mag) * grid_lim], [(w_pred[1] / w_pred_mag) * grid_lim],
               scale=1, units='xy', color='r')
    plt.annotate('w_pred', xy=w_pred[0] / w_pred_mag * grid_lim + [0., 0.1], fontsize=12, color='r')
    plt.plot([grid_lim, -grid_lim], [calc_x2(b, grid_lim, w_pred), calc_x2(b, -grid_lim, w_pred)],
             color='r', label='pred decision line')

    plt.title(f'True and predicted decision line')
    plt.xlim(-grid_lim, grid_lim)
    plt.ylim(-grid_lim, grid_lim)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid()
    plt.show()

In [ ]:
N, d = 500, 2 # count of observations and features
np.random.seed(1)
x = np.random.rand(N, d)
x -= np.mean(x) # by subtracting mean, we move the features to range [-0.5, 0.5]
#x = np.hstack([ x, np.ones((N, 1)) ]) # Add constant dimension -- a column of 1s at the end

w_true = np.random.rand(1,d) # generate w from which we compute labels
w_true -= np.mean(w_true) # Only rotates the weight vector in 2d space

y_true = np.sign(w_true.dot(x.T))[0]
y_true[0] = -1 * y_true[0] # this makes a separation line impossible to compute and we can plot both w_true and w_pred distinctly

w_pred, b = perceptron(x, y_true)
y_pred = classify_linear_grader(x, w_pred, b).astype(int)

plot_perceptron_2D(x, y_true, w_true, y_pred, w_pred, b)

NameError: ignored

In [ ]:
# number of input vectors
N = 100

# generate random (linarly separable) data
xs = np.random.rand(N, 2)*10-5

# defining random hyperplane
w0 = np.random.rand(2)
b0 = np.random.rand()*2-1;

# assigning labels +1, -1 labels depending on what side of the plane they lie on
ys = np.sign(xs.dot(w0)+b0)

# call perceptron to find w from data
w,b = perceptron(xs.copy(),ys.copy())

# test if all points are classified correctly
assert (all(np.sign(ys*(xs.dot(w)+b))==1.0))  # yw'x should be +1.0 for every input
print("Looks like you passed the Perceptron test!")

# we can make a pretty visualization
visboundary(w,b,xs,ys)

Looks like you passed the Perceptron test!


NameError: ignored

### **Part Three: Make Predictions** [Graded]
Implement classify_linear that applies the weight vector (with implicit bias term) to the input vector. Make sure that the predictions returned are either 1 or -1.

In [ ]:
def classify_linear(xs,w,b=None):
    """
    function preds=classify_linear(xs,w,b)

    Make predictions with a linear classifier
    Input:
    xs : n input vectors of d dimensions (nxd) [could also be a single vector of d dimensions]
    w : weight vector of dimensionality d
    b : bias (scalar)

    Output:
    preds: predictions (1xn)
    """
    w = w.flatten()
    predictions=np.zeros(xs.shape[0])

    predictions = np.sign(np.dot(w, xs)+b)

    raise NotImplementedError()
    return predictions

In [ ]:
def classify_linear(xs,w,b=None):
    """
    function preds=classify_linear(xs,w,b)

    Make predictions with a linear classifier
    Input:
    xs : n input vectors of d dimensions (nxd) [could also be a single vector of d dimensions]
    w : weight vector of dimensionality d
    b : bias (scalar)

    Output:
    preds: predictions (1xn)
    """
    w = w.flatten()
    predictions=np.zeros(xs.shape[0])

    if b is None:
      predictions = np.sign(w@xs.T)
    if b is not None:
      predictions = np.sign((w@xs.T)+b)

    raise NotImplementedError()
    return predictions

In [ ]:
def classify_linear(xs,w,b=None):
    """
    function preds=classify_linear(xs,w,b)

    Make predictions with a linear classifier
    Input:
    xs : n input vectors of d dimensions (nxd) [could also be a single vector of d dimensions]
    w : weight vector of dimensionality d
    b : bias (scalar)

    Output:
    preds: predictions (1xn)
    """
    w = w.flatten()
    predictions=np.zeros(xs.shape[0])

    for i in range(xs.shape[0]):
      if np.dot(w,xs[i]) + b >=0:
        predictions[i] = 1
      if np.dot(w,xs[i]) + b <0:
        predictions[i] = -1

    raise NotImplementedError()
    return predictions

In version above, we get the error "Your code raises the following exception:
 TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'". This error message indicates that the b argument is None and you are trying to add it to a float value. To fix the error, you can add a check to see if b is not None before using it in your code. Here's a modified version of your function:


In this version below, we first check if b is not None, and if it is not, we add it to the dot product of w and xs[i] to get the value of y. If b is None, we skip adding it to the dot product.

In [ ]:
def classify_linear(xs,w,b=None):
    """
    function preds=classify_linear(xs,w,b)

    Make predictions with a linear classifier
    Input:
    xs : n input vectors of d dimensions (nxd) [could also be a single vector of d dimensions]
    w : weight vector of dimensionality d
    b : bias (scalar)

    Output:
    preds: predictions (1xn)
    """
    w = w.flatten()
    predictions=np.zeros(xs.shape[0])

    for i in range(xs.shape[0]):
        if b is not None:
            y = np.dot(w,xs[i]) + b
        else:
            y = np.dot(w,xs[i])
        if y >=0:
            predictions[i] = 1
        if y < 0:
            predictions[i] = -1

    return predictions

In [ ]:
def classify_linear(xs,w,b=None):
    """
    function preds=classify_linear(xs,w,b)

    Make predictions with a linear classifier
    Input:
    xs : n input vectors of d dimensions (nxd) [could also be a single vector of d dimensions]
    w : weight vector of dimensionality d
    b : bias (scalar)

    Output:
    preds: predictions (1xn)
    """
    w = w.flatten()
    predictions=np.zeros(xs.shape[0])

    for i in range(xs.shape[0]):
        if b is None:
            predictions[i] += np.sign(np.dot(w,xs[i]))
        else:
            predictions[i] += np.sign(np.dot(w,xs[i])+b)
    return predictions

    raise NotImplementedError()

## Scikit-learn approach

[Scikit-learn](https://scikit-learn.org/stable/index.html) (or `sklearn`) is a Python library with implementations for numerous machine learning and data science models. Scikit-learn provides a standard step-by-step training procedure across different machine learning models, simplifying model training and prediction. The typical process for selecting, training, and predicting with a model of your choice is as follows:


1. Define the classifier `clf` using a call to the model class.
2. Train `clf` using `clf.fit` on training data.
3. Predict on test data using `clf.predict`, getting predictions as output.

Scikit-learn provides a [perceptron model](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Perceptron.html). We provide a brief demonstration of its usage below.